#Arreglos y clases

## Matrices

Una matriz es un arreglo de mxn elementos.


\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}


In [1]:
#Estamos creando una lista de listas (matriz)
A = [[1,2,3],[4,5,6],[7,8,9]]
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [2]:
type(A)

list

In [3]:
#Vamos a crear otra lista de listas
B = [[21,34,40],[71,17,77],[63,81,28]]
print(B)

[[21, 34, 40], [71, 17, 77], [63, 81, 28]]


In [5]:
#Suma las listas pero en una concatenación.
A+B
print(A+B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 34, 40], [71, 17, 77], [63, 81, 28]]


In [6]:
#Igual en una concatenación, pero ahora junta dos veces la misma.
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
#Te da la primera columna
A[0]

[1, 2, 3]

In [9]:
#No se puede iterar A[0,0], sino que tiene que ser como se muestra abajo; y sirve para seleccionar la columna y el número Ej: A[0][0] = A1,1.
A[0][0]

1

##Vectores y listas

In [10]:
#De igual manera lo concatena.
L = A[0]
M = B[0]
L+M
print(L+M)


[1, 2, 3, 21, 34, 40]


In [12]:
#lo que se hace es asignar el valor de L[0] a una variable a y esa es igual a A[0][0], L y M son listas.
a = L[0]
print(a)

1


In [13]:
#al sumar los dos elementos ya implementados en varaibles, te da la operación de la suma
b = M[0]
a+b
print(a+b)

22


In [14]:
#Al hacer la comparación te da la respuesta la cual es un booleano.
a == 1

True

### Suma de "vectores"

In [15]:
#Se verifica que la cardinalidad de ambas sea la misma.
len(L) == len(M)

True

In [16]:
#Lo que se hace es ir sumando cada elemento dentro de una lista.
suma = [L[0] + M[0], L[1] + M[1], L[2] + M[2]]
print(suma)

[22, 36, 43]


In [18]:
#Se puede hacer una suma de la siguiente manera con un bucle (for).
suma = [L[i]+ M[i] for i in range(3)]
print(suma)

[22, 36, 43]


#### Creación de funciones globales

La función para crear funciones es `def` que se cierra con un debug (`print` o `return`)

In [21]:
# def sirve para crear funciones, el hola() almacena un texto que se imprime solo invocando la función.
def hola():
  print("Hola, me llamo Fabrizio")

In [23]:
hola()

Hola, me llamo Fabrizio


In [28]:
#Se establecen parámetros como si fueran variables.
def Saludar(s,n):
  print(f"Hola, me llamo {s} y tengo {n} años")

In [29]:
#Se invoca a la función y se ponen los parámetros deseados.
Saludar("Cesar", 18)

Hola, me llamo Cesar y tengo 18 años


In [33]:
# Se crea una función en la que se busca establecer los números que son par e impar.
def par():
  for x in range(10):
    if x%2 == 0:
      print(f"{x} es par")
    else:
      print(f"{x} es impar")

In [34]:
par()

0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


In [35]:
def suma_vectorial(L, M):
  x = [L[i]+ M[i] for i in range(len(L))]
  return x

In [36]:
L = [1, 2, 3]
M = [21, 34, 40]

suma_vectorial(L,M)

[22, 36, 43]

## Módulos o librerías

In [38]:
#el asterisco muestra todos los elementos de la librería, from math import *
import math
from math import sqrt, pi

In [39]:
sqrt(68)

8.246211251235321

In [40]:
pi

3.141592653589793

# El módulo NumPy

La función array

In [41]:
#La función array es un convertidor, convierte una lista en un vector.
import numpy as np

L_vector = np.array(L)
M_vector = np.array(M)

L_vector + M_vector

array([22, 36, 43])

In [43]:
#Se escriben las matrices de la siguiente manera y posteriormente se usa el .reshape para acomodar la matriz segun la cantidad de filas y columnas.
C = [9,2,2,2,3,3,2,17,2]
A = [8,1,1,1,2,2,1,16,1]

C_matriz = np.array(C).reshape(3,3)
A_matriz = np.array(A).reshape(3,3)

print(C_matriz)
print(A_matriz)



[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [44]:
#El @ sirve para hacer la multiplicación de matrices.
C_matriz @ A_matriz

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])

In [45]:
#Al no ser conmutativas se hacen las dos operaciones.
A_matriz @ C_matriz

array([[76, 36, 21],
       [17, 42, 12],
       [43, 67, 52]])